apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: custom-namespace-recording-rules
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:

  - name: custom.namespace.rules

    interval: 30s

    rules:

    - record: custom:namespace_cpu_usage
      expr: |
        sum by(namespace)
        (
          rate(container_cpu_usage_seconds_total[5m])
        )

    - record: custom:namespace_memory_usage
      expr: |
        sum by(namespace)
        (
          container_memory_working_set_bytes
        )

    - record: custom:namespace_pod_count
      expr: |
        count by(namespace)
        (
          kube_pod_info
        )
