apiVersion: v1
kind: Pod
metadata:
  name: restore-test
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: restore-volume
  volumes:
  - name: restore-volume
    persistentVolumeClaim:
      claimName: restored-pvc
