apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-4-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Ashish420-tech/Devops-100-Project.git
    targetRevision: project-4-gitops-demo
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
