groups:

- name: infrastructure.node

  rules:

  - alert: NodeDown

    expr: up{job="node-exporter"} == 0

    for: 2m

    labels:
      severity: critical

    annotations:
      summary: "Node exporter is unreachable"

      description: "Prometheus cannot scrape node exporter."
 

  - alert: KubernetesNodeNotReady

  expr: kube_node_status_condition{condition="Ready",status="true"} == 0

  for: 5m

  labels:
    severity: critical

  annotations:
    summary: "Node is NotReady"

    description: "A Kubernetes node has remained NotReady for more than 5 minutes."
