apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-4-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=nginx:latest
    argocd-image-updater.argoproj.io/nginx.update-strategy: latest
spec:
  project: default

  source:
    repoURL: https://github.com/Ashish420-tech/Devops-100-Project.git
    targetRevision: project-4-gitops-demo
    path: project-4-gitops-demo/helm-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
