pipeline {
    agent any

    environment {
        IMAGE_NAME = "ashishmondal420/multi-env-app"
    }

    stages {
        stage('Test') {
            steps {
                dir('assignment-01-docker-flask-app') {
                    sh '''
                        pwd
                        ls -la
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r app/requirements.txt
                        pip install pytest
                        pytest tests/
                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('assignment-01-docker-flask-app') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $IMAGE_NAME
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker rm -f flask-app || true
                    docker run -d --name flask-app -p 5000:5000 ashishmondal420/multi-env-app
                '''
            }
        }
    }
}
