pipeline {
    agent any

    environment {
        IMAGE_NAME = "ashishmondal420/flask-devsecops-app"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'assignment-01-docker-flask-app',
                url: 'https://github.com/Ashish420-tech/Devops-100-Project.git'
            }
        }

        stage('Test') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install -r app/requirements.txt
                pip install pytest
                pytest tests/
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $IMAGE_NAME
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker rm -f flask-app || true
                docker run -d --name flask-app -p 5000:5000 $IMAGE_NAME
                '''
            }
        }
    }
}
